### ISSUE TITLE
ヘッダー画像及びテキストを検討する

### ISSUE THREAD

**Issue by miya0001** [space-apps-kushimoto/space-apps-kushimoto.github.io#3]
![](https://www.evernote.com/l/ABWy7MVb2HlGhqZAGA0B0NZ5ctINs7EfeL4B/image.png)

画像は NASA のオープンデータを使うのがいいかな。
特定可能な人物が写ってる写真は、肖像権の問題等が別途発生するので注意。

**Comment by kwaka1208** [comment]
串本でやるんやでってことがわかるビジュアル入れたいですね。
