### ISSUE TITLE
トップページ上のコンテンツを検討

### ISSUE THREAD

**Issue by miya0001** [space-apps-kushimoto/space-apps-kushimoto.github.io#4]
![](https://www.evernote.com/l/ABXKWiwn7v1BeYp5VpdLVXS_E6Pm_UooRpMB/image.png)

**Comment by nztm** [comment]
サイトのコンテンツに必要だと思われるものをまとめました。

ABOUT
-Space Apps Challengeについて
-開催概要
-Google Map
-参加リンク(compassなどの)

審査員
実行委員メンバー
スポンサー

Footer 
・SNSボタン
　　Twitter
　　Facebook
